@extends('layouts.public')
@inject('library', 'App\Services\MemberLibrary')
@section('title', ucfirst($kind).' | FanHub Plus')
@section('content')
<div class="member-discovery"><header class="member-page-heading"><p><a href="{{ route('home') }}">HOME</a> / {{ strtoupper($kind) }}</p><h1>{{ $title }}</h1><span>{{ $intro }}</span></header>
<form class="member-filters" method="get" role="search"><label>Search<input type="search" name="q" value="{{ $filters['q'] ?? '' }}" maxlength="120" placeholder="Find your favorites"></label><label>Fandom<select name="category"><option value="">All fandoms</option>@foreach($categories as $category)<option value="{{ $category->slug }}" @selected(($filters['category'] ?? '') === $category->slug)>{{ $category->name }}</option>@endforeach</select></label>
@if($kind === 'multimedia')<label>Format<select name="type"><option value="">All media</option>@foreach(['image' => 'Images & fan art', 'video' => 'Videos & trailers', 'audio' => 'Audio & soundtracks'] as $value => $label)<option value="{{ $value }}" @selected(($filters['type'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></label><label>Genre / tag<select name="tag"><option value="">All tags</option>@foreach($tags as $tag)<option value="{{ $tag->id }}" @selected(($filters['tag'] ?? '') == $tag->id)>{{ $tag->name }}</option>@endforeach</select></label><label>Release year<input type="number" name="year" min="1900" max="2200" value="{{ $filters['year'] ?? '' }}" placeholder="Any year"></label>@endif
<label>Sort by<select name="sort"><option value="latest">Latest</option>@if($kind === 'multimedia')<option value="popular" @selected(($filters['sort'] ?? '') === 'popular')>Most popular</option>@endif<option value="alphabetical" @selected(($filters['sort'] ?? '') === 'alphabetical')>A to Z</option></select></label><button class="member-button">Find {{ $kind === 'characters' ? 'characters' : 'media' }}</button><a href="{{ route('public.section', $kind) }}">Clear filters</a></form>
@include('user.partials.messages')<p class="member-muted" style="margin-bottom:20px">{{ $items->total() }} results</p><div class="member-collection-grid">@forelse($items as $item)<x-member-card :card="$library->card($item)" />@empty<div class="member-panel member-empty"><h2>No matches just yet.</h2><p>Try another search or clear your filters to see everything.</p></div>@endforelse</div>@include('user.partials.pagination', ['paginator' => $items])</div>
@endsection
