@extends('user.layout', ['pageTitle' => $submission->exists ? 'Edit Submission' : 'New Submission'])
@section('member-content')
<header class="member-page-heading"><p>THE COMMUNITY DESK</p><h1>{{ $submission->exists ? 'Give it another chapter.' : 'Something worth sharing.' }}</h1><span>Bring your perspective, artwork or discoveries to the community.</span></header>
<div class="member-editor-layout"><form class="member-panel member-form" action="{{ $submission->exists ? route('user.submissions.update', $submission) : route('user.submissions.store') }}" method="post" enctype="multipart/form-data">@csrf @if($submission->exists) @method('PUT') @endif
<label>Title<input name="title" value="{{ old('title', $submission->title) }}" maxlength="180" required placeholder="Give your contribution a title"></label>
<div class="member-form-grid"><label>Fandom<select name="category_id" required><option value="">Choose a fandom</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $submission->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></label><label>Content type<select name="type">@foreach(['article' => 'Article', 'image' => 'Fan art / image', 'video' => 'Video', 'audio' => 'Audio'] as $value => $label)<option value="{{ $value }}" @selected(old('type', $submission->type) === $value)>{{ $label }}</option>@endforeach</select></label></div>
<label>Short introduction<textarea name="excerpt" maxlength="500" rows="2" placeholder="A little context for your readers…">{{ old('excerpt', $submission->excerpt) }}</textarea></label>
<label>Your story / description<textarea name="body" rows="12" minlength="30" maxlength="50000" required placeholder="Tell your story in your own words…">{{ old('body', $submission->body) }}</textarea></label>
<div class="member-form-grid"><label>Cover image <small>Optional · JPG, PNG, WebP, GIF · up to 5 MB</small><input type="file" name="cover" accept="image/jpeg,image/png,image/webp,image/gif"></label><label>Media attachment <small>Image, video or audio · up to 20 MB</small><input type="file" name="attachment" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,audio/mpeg,audio/wav,audio/ogg,audio/mp4"></label></div>
@if($submission->exists && $submission->media->isNotEmpty())<p class="member-muted">Current files: {{ $submission->media->pluck('original_filename')->implode(', ') }}. Leave a file field empty to keep its current attachment.</p>@endif
<div class="member-actions"><button class="member-button" name="intent" value="submit">Submit for review →</button><button class="member-button member-button--quiet" name="intent" value="draft">Save draft</button><a href="{{ route('user.submissions') }}">Cancel</a></div>
</form><aside class="member-panel member-editor-note"><span class="member-kicker">BEFORE YOU SHARE</span><h2>A few thoughtful details.</h2><p>Share work you created or have permission to use. Credit your sources and keep the conversation welcoming.</p><p>Images, videos and audio need an attachment. Articles can be submitted with text alone.</p><p>You can save a draft and return later. Submitted work stays private until a moderator approves it.</p></aside></div>
@endsection
